### ISSUE TITLE
resolutions issue

### ISSUE THREAD

**Issue by EndeBy** [vortisrd/trew_hud_ui#1]
How can i solve this? Any way they all look the same?

1080p user: https://gyazo.com/b65df98623b1730255b1cc446a93858c
900p user: http://prntscr.com/q3csfq
720p user: https://gyazo.com/139335dcfbbc2450124b6aec9bb15e70

**Comment by vortisrd** [comment]
This his not an issue. You changed status position manually, probably using the "TOP" property on CSS. The TOP property positions from top to bottom, so when you change it, it will be relative to the top.

If you want them to appear at the bottom, change TOP to BOTTOM and tweak it until you get it.
