### ISSUE TITLE
No hud

### ISSUE THREAD

**Issue by yagizher** [vortisrd/trew_hud_ui#11]
Hey. I downloaded it and started, but no money or anything shows up. Just the speedometer shows up when i enter a car. Any helps asap please?

**Comment by xnubil** [comment]
Make sure the resource is running before you log into server. It pulls all the information when player joins.

**Comment by yagizher** [comment]
what? didnt get it

**Comment by yagizher** [comment]
im starting hud after everything.

**Comment by hemato** [comment]
same issue for me.. any help ?

**Comment by LuLisTaken** [comment]
same issue
