### ISSUE TITLE
issue showing socity fund

### ISSUE THREAD

**Issue by stephen9898** [vortisrd/trew_hud_ui#14]
shows 2 times https://prnt.sc/qp7cxv

**Comment by nanthu98** [comment]
Same here

**Comment by vortisrd** [comment]
> shows 2 times https://prnt.sc/qp7cxv

That's not a bug. On the secion POST INSTALLATION on my ESX Instructions, I tell you how to disable the default ESX UI.

**Comment by stephen9898** [comment]
i do and still comes up
