### ISSUE TITLE
Adding fuel meter to boats, planes and heli

### ISSUE THREAD

**Issue by kevintransp** [vortisrd/trew_hud_ui#15]
Really nice hud you made.
Iam working on fuel for helicopters, planes and boats but i can't get the hud to show the meter.

I have added the vehicle classes to client.lua and looked at the fuel code stuff but can't find where to add.
Could you please be so kind to give some more information?

**Comment by vortisrd** [comment]
I've disabled it on vehicles that has fuel treatment different the default one.

Go to the client.lua section and search for the part I verify if the vehicle is a boat, plane and etc and delete the code I use to disable the fuel ui.

**Comment by kevintransp** [comment]
Thanks for your answer.
Where exactly to find that code?

Is it `local vehicleClass = GetVehicleClass(vehicle)`
I have set all classes of vehicles in here
`local vehiclesCars = {0,1,2,3,4,5,6,7,8,9,10,11,12,17,18,19,20};`

**Comment by kevintransp** [comment]
Maybe you could provide me with an answer?
