### ISSUE TITLE
Problem with server.lua

### ISSUE THREAD

**Issue by railroadnl** [vortisrd/trew_hud_ui#16]
The resource is great
but when i start it 
I see in my server the following error.

`SCRIPT ERROR: @hud/server/server.lua:25: attempt to call a nil value (field 'getBank')`

How can i fix that.

I have already tried to fix it with a all the requirements
but thats not working

**Comment by HezimX** [comment]
change line 25 in server.lua

`			bankMoney = xPlayer.getAccount('bank').money,`
