### ISSUE TITLE
fix the le problem 

### ISSUE THREAD

**Issue by christopher19049** [vortisrd/trew_hud_ui#17]
how I can fix the problem
SCRIPT ERROR: @trew_hud_ui/server/server.lua:25: attempt to call a nil value (field 'getBank')

**Comment by meistroburger** [comment]
I also get a lot of errors with => @trew_hud_ui/server/server.lua:25: attempt to call a nil value (field 'getBank')

**Comment by Duqino** [comment]
Same here. I think it has something to do with esx update.

Also the job name is not showing up. Its says jobname and nothing els.

My older server has no problems at all. Just started making a brand new server.

**Comment by Duqino** [comment]
@christopher19049 
@meistroburger 

https://github.com/vortisrd/trew_hud_ui/issues/16

**Comment by vortisrd** [comment]
@christopher19049 @Duqino @meistroburger IT'S NOT A BUG!!!!!!!

In fact, ESX removed the function to get money (getMoney()) from the bank in their new versions hence why it's not working now.

I've set up a fix on server.lua. It should work now.
