### ISSUE TITLE
ESX Version: Money, Bank, BlackMoney Checks cause Lag

### ISSUE THREAD

**Issue by azarathkhan** [vortisrd/trew_hud_ui#19]
Hello! I love your HUD very much, however I have found the trew_hud_ui:getServerInfo which is triggered every 1 second by the client side .lua creates alot of server side lag.

Might I suggest using esx client side triggers to get updates on money such as:
RegisterNetEvent('esx:setAccountMoney')
RegisterNetEvent('esx:playerLoaded')
RegisterNetEvent('es:activateMoney')

I will be making the changes to my version of the HUD to increase performance, as it will remove the need for a while loop triggered server event.

**Comment by vortisrd** [comment]
Hey @azarathkhan , thank you for reaching out!

In fact, it was like that for a while, but I decided to change it way back. While I was testing on a 1280 slots server, it didn't had much lag or hitches. But it seems with changes coming from FiveM and ESX made it that way.

I'm not active on FiveM development anymore. I just fix some stuff here and there, but once you get it right, feel free to make a pull request and I'll merge in the branch, crediting you, ok?

Again, thank you.

**Comment by azarathkhan** [comment]
Will do! Thanks for the reply.
