### ISSUE TITLE
display problem

### ISSUE THREAD

**Issue by JingJayYu** [vortisrd/trew_hud_ui#28]
my trew hud ui it wont display byitself
i must type /toggleui to display

**Comment by Richards0nd** [comment]
I also have the same problem, the HUD does not appear, and even if I type the command to make it visible, it does not show all the information
https://uploads.richardsondouglas.com.br/FiveM_GTAProcess_FQurmJSqKB.jpg

**Comment by xxfili00** [comment]
I also have the same problem or that hud does not appear

**Comment by llura1** [comment]
yeah so do I, It seems like the car speedometer works, nothing else does but the society money.
