### ISSUE TITLE
SCRIPT ERROR

### ISSUE THREAD

**Issue by Irkutsk38** [vortisrd/trew_hud_ui#7]
Hello. Gives me an error:

MainThrd/ ^1SCRIPT ERROR: @trew_hud_ui/client/client.lua:836: attempt to index a nil value (field '?')^7
MainThrd/ ^3> fn^7 (^5@trew_hud_ui/client/client.lua^7:83)

**Comment by vortisrd** [comment]
That line on client.lua for ESX is responsible for the data format. On VRP/VRPEX, it doesn't exist.
If you delete any lines on config.lua or modified the script in any way, download it again and follow the instructions.
